service: plankton-auth


package:
  exclude: 
    - data/**
    - .vscode/**
    - .idea/**
    - README.md
    - bin
    - bitbucket-pipelines.yml
    - .eslintrc
    - jest-dynalite-config.js
    - jest.config.json
  include:
    - '*.key'
    - '*.pub'
  individually: true

custom:
  stage: ${opt:stage, 'staging'}
  region: 'sa-east-1'
  serverless-offline:
    httpPort: 3000
    noPrependStageInUrl: true
  esbuild:
    bundle: true
    sourcemap: true
    minify: false
    packager: yarn
    watch:
      pattern: 'src/**/*.ts'
      ignore: '**/*.test.ts'
  swaggerApi:
    swagger: ${file(docs/swagger.yaml)}
  customDomain:
    domainName: auth.planktondoc.com
    stage: ${self:custom.stage}
    basePath: ${self:custom.stage}
    certificateName: 'planktondoc.com'
    createRoute53Record: true
    createRoute53IPv6Record: true
    endpointType: REGIONAL
    securityPolicy: tls_1_2
    apiType: rest
    autoDomain: true
  staging:
    stage: staging
    logRetentionInDays: 5
    userPool: plankton-pool-staging
    userClient: plankton-client-staging
  production:
    stage: production
    logRetentionInDays: 60
    userPool: plankton-pool-production
    userClient: plankton-client-production

provider:
  name: aws
  runtime: nodejs16.x
  versionFunctions: false
  stage: ${self:custom.stage}
  region: 'sa-east-1'
  endpointType: REGIONAL
  environment:
    REGION: ${self:custom.region}
    STAGE: ${self:custom.${self:custom.stage}.stage}
    NODE_OPTIONS: --enable-source-maps
    USER_POOL_ID: { Ref: UserPool }
    USER_CLIENT_ID: { Ref: UserClient }
    GITHUB_API_URL: https://api.github.com
    GITHUB_LOGIN_URL: https://github.com
    COGNITO_REDIRECT_URI: https://plankton.auth.sa-east-1.amazoncognito.com/oauth2/idpresponse
    GITHUB_CERT_PUBLIC: github.pub
    GITHUB_CERT_KEY: github.key
  deploymentBucket:
    name: serverless.tag.deployment

functions:
  githubAuthorize:
    handler: src/functions/github/authorizer.handler
  githubToken:
    handler: src/functions/github/token.handler
  githubUser:
    handler: src/functions/github/userInfo.handler
  githubJwks:
    handler: src/functions/github/jwks.handler
  cognitoPreSignUp:
    handler: src/functions/cognito/preSignUp.handler
    events:
      - cognitoUserPool:
          pool: ${self:custom.${self:custom.stage}.userPool}
          trigger: PreSignUp
    iamRoleStatementsInherit: true
    iamRoleStatements:
      - Effect: Allow
        Action: 
          - cognito-idp:AdminAddUserToGroup
          - cognito-idp:AdminUpdateUserAttributes
          - cognito-idp:ListUsers
          - cognito-idp:AdminLinkProviderForUser
          - cognito-idp:AdminCreateUser
          - cognito-idp:AdminSetUserPassword
        Resource:
          - Fn::GetAtt: UserPool.Arn

resources:
  Resources:
    UserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        UserPoolName: ${self:custom.${self:custom.stage}.userPool}
        Schema:
          - Name: email
            Required: true
            Mutable: true
        Policies:
          PasswordPolicy:
            MinimumLength: 6
        AutoVerifiedAttributes: ["email"]

    UserClient:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        ClientName: ${self:custom.${self:custom.stage}.userClient}
        GenerateSecret: false
        UserPoolId: { Ref: UserPool }
        AccessTokenValidity: 5
        IdTokenValidity: 5

plugins:
  - serverless-esbuild
  - serverless-offline
  - serverless-plugin-swagger-api
  - serverless-plugin-log-retention
  - serverless-iam-roles-per-function
  - serverless-domain-manager