process.env.STAGE = 'staging'
process.env.USER_CLIENT_ID = 'plankton-client-staging'
process.env.SECRET_GITHUB_ID = 'plankton-production/github'
process.env.GITHUB_LOGIN_URL = 'https://github.com'
process.env.GITHUB_API_URL = 'https://api.github.com'
