process.env.STAGE = 'staging'
process.env.USER_CLIENT_ID = 'plankton-client-staging'
process.env.GITHUB_LOGIN_URL = 'https://github.com'
process.env.GITHUB_API_URL = 'https://api.github.com'
process.env.GITHUB_CERT_KEY = 'github.key'
process.env.GITHUB_CERT_PUBLIC = 'github.pub'
process.env.TABLE_IDENTITY = 'plankton-identity-staging'
process.env.GITHUB_PROVIDER_NAME = 'Github-staging'
