name: Install packages
description: 'Install node packages'
runs:
  using: "composite"
  steps:
    - name: Install node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'
        cache: 'yarn'

    - name: Enable cache for packages
      id: cache
      uses: actions/cache@v2
      with:
        key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
        path: |
          ${{ github.workspace }}/.yarn
          ${{ github.workspace }}/node_modules

    - name: Install packages
      if: steps.cache.outputs.cache-hit != 'true'
      shell: bash
      run: yarn install